module.exports = [
  {
    _id: "ID1",
    name: "Алексей Иванов",
    profession: "Финансовый аналитик",
    qualities: "Самостоятельность",
    rating: 13,
    isArchived: false,
    bookmark: false,
    category: 1,
  },
  {
    _id: "ID2",
    name: "Вадим Смирнов",
    profession: "DevOps-инженер",
    qualities: "Инициативность",
    rating: 10,
    isArchived: false,
    bookmark: false,
  },

  {
    _id: "ID3",
    name: "Валентин Попов",
    profession: "Дизайнер",
    qualities: "Ответственность",
    rating: 20,
    isArchived: false,
    bookmark: false,
    category: 2,
  },
  {
    _id: "ID4",
    name: "Руслан Чертов",
    profession: "Веб-разработчик",
    qualities: "Внимательность",
    rating: 15,
    isArchived: false,
    bookmark: false,
    category: 1,
  },
  {
    _id: "ID5",
    name: "Данил Петров",
    profession: "Блогер",
    qualities: "Мобильность",
    rating: 42,
    isArchived: false,
    bookmark: false,
    category: 3,
  },
  {
    _id: "ID6",
    name: "Леонид Морозов",
    profession: "Таргетолог",
    qualities: "Креативность",
    rating: 27,
    isArchived: false,
    bookmark: false,
    category: 2,
  },
  {
    _id: "ID7",
    name: "Никита Козлов",
    profession: "Бизнес-аналитик",
    qualities: "Храбрость",
    rating: 23,
    isArchived: false,
    bookmark: false,
    category: 2,
  },
  {
    _id: "ID8",
    name: "Олег Егоров",
    profession: "Инженер",
    qualities: "Честность",
    rating: 14,
    isArchived: false,
    bookmark: false,
    category: 1,
  },
  {
    _id: "ID9",
    name: "Сергей Степанов",
    profession: "Аналитик данных",
    qualities: "Гибкость",
    rating: 50,
    isArchived: false,
    bookmark: false,
    category: 3,
  },
  {
    _id: "ID10",
    name: "Кирилл Новиков",
    profession: "Разработчик С++",
    qualities: "Надежность",
    rating: 19,
    isArchived: false,
    bookmark: false,
    category: 1,
  },
  {
    _id: "ID11",
    name: "Леонид Михайлов",
    profession: "SMM-менеджер",
    qualities: "Порядочность",
    rating: 30,
    isArchived: false,
    bookmark: false,
    category: 3,
  },
  {
    _id: "ID12",
    name: "Денис Соколов",
    profession: "Копирайтер",
    qualities: "Трудолюбие",
    rating: 31,
    isArchived: false,
    bookmark: false,
    category: 3,
  },
];
